apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
        - image: northamerica-northeast2-docker.pkg.dev/woven-operative-451316-c7/sofe3980u/binarycalculator
          name: binarycalculator
          ports:
            - containerPort: 8080
              name: bin-calc
